services:
  - type: web
    name: simulador-gpon-hfc
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SOCKETIO_ASYNC_MODE
        value: threading
      - key: SECRET_KEY
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: ADMIN_EMAILS
        value: jonatansilvaromao@gmail.com
      - key: FLASK_DEBUG
        value: false
