"""ajuste respostas para simulados livres

Revision ID: 1753626895e5
Revises: c39cfa4172e6
Create Date: 2026-03-19 12:09:00.822390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753626895e5'
down_revision = 'c39cfa4172e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banco', sa.String(length=20), nullable=True))
        batch_op.alter_column('turma_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matricula_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.alter_column('matricula_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('turma_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('banco')

    # ### end Alembic commands ###
