"""add cpf to alunos

Revision ID: 332e607d7f40
Revises: 3d398b4bf5d7
Create Date: 2026-03-19 07:36:08.186725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332e607d7f40'
down_revision = '3d398b4bf5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['cpf'])

    with op.batch_alter_table('questoes_turma', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questoes_turma_turma_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'turmas', ['turma_id'], ['id'])

    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('respostas_turma_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('respostas_matricula_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'turmas', ['turma_id'], ['id'])
        batch_op.create_foreign_key(None, 'matriculas', ['matricula_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('respostas_matricula_id_fkey'), 'matriculas', ['matricula_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('respostas_turma_id_fkey'), 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questoes_turma', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questoes_turma_turma_id_fkey'), 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
