"""Adiciona campo tipo em Resposta

Revision ID: 6646f91df3ac
Revises: 1753626895e5
Create Date: 2026-03-19 13:39:46.876293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6646f91df3ac'
down_revision = '1753626895e5'
branch_labels = None
depends_on = None


def upgrade():
    # 1. cria a coluna permitindo nulos
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('tipo', sa.String(length=20), nullable=True)
        )

    # 2. atualiza os registros antigos
    op.execute("UPDATE respostas SET tipo = 'turma' WHERE turma_id IS NOT NULL;")
    op.execute("UPDATE respostas SET tipo = 'livre' WHERE turma_id IS NULL;")

    # 3. aplica a restrição NOT NULL
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.alter_column('tipo', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
