"""add cascade delete to turma/matricula

Revision ID: 68d0f30fec0e
Revises: f32a3621dfdd
Create Date: 2026-03-15 00:07:45.148310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d0f30fec0e'
down_revision = 'f32a3621dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('matriculas_turma_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('matriculas_turma_id_fkey'), 'turmas', ['turma_id'], ['id'])

    # ### end Alembic commands ###
