"""Add premium fields to Professor

Revision ID: 6cf2367134c3
Revises: ed1630ed3ca6
Create Date: 2026-04-04 20:33:21.469300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf2367134c3'
down_revision = 'ed1630ed3ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('premium_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('premium_expires_at')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
