"""Corrige coluna questao -> questao_id

Revision ID: c39cfa4172e6
Revises: 332e607d7f40
Create Date: 2026-03-19 09:41:43.391021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39cfa4172e6'
down_revision = '332e607d7f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.alter_column('resposta',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('respostas_turma_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('respostas_matricula_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'matriculas', ['matricula_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('respostas_matricula_id_fkey'), 'matriculas', ['matricula_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('respostas_turma_id_fkey'), 'turmas', ['turma_id'], ['id'])
        batch_op.alter_column('resposta',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###
